kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: hac-proxy
parameters:
  - name: NAMESPACE
    required: true
  - name: ENV_NAME
    required: true
  - name: HOSTNAME
    required: true
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        service.beta.openshift.io/serving-cert-secret-name: hac-proxy-cert
      name: hac-proxy
      namespace: ${NAMESPACE}
    spec:
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: hac-proxy
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      annotations:
        haproxy.router.openshift.io/rewrite-target: /
      labels:
        frontend: hac-proxy
      name: hac-proxy
      namespace: ${NAMESPACE}
    spec:
      ingressClassName: openshift-default
      rules:
        - host: ${HOSTNAME}
          http:
            paths:
              - path: /api/k8s
                pathType: Prefix
                backend:
                  service:
                    name: hac-proxy
                    port:
                      number: 8080
              - path: /wss/k8s
                pathType: Prefix
                backend:
                  service:
                    name: hac-proxy
                    port:
                      number: 8080
      tls:
        - {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: hac-proxy
      namespace: ${NAMESPACE}
    spec:
      progressDeadlineSeconds: 600
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        matchLabels:
          app: hac-proxy
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: hac-proxy
        spec:
          containers:
            - env:
                - name: HJ_K8S
                  value: https://api-toolchain-host-operator.apps.hac-devsandbox.5unc.p1.openshiftapps.com
                - name: HJ_SERVE
                  value: :8080
                - name: HJ_SSL
                  value: 'false'
              image: quay.io/psav/hac-proxy:098a9d8
              imagePullPolicy: Always
              name: hac-proxy
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /tmp/certs
                  name: cert
                  readOnly: true
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
            - name: cert
              secret:
                defaultMode: 420
                secretName: hac-proxy-cert
