export const TOOLBAR_HEIGHT = 40;
export const DROP_SHADOW_SPACING = 5;

export const DEFAULT_NODE_WIDTH = 165;
export const DEFAULT_NODE_HEIGHT = 32;
export const DEFAULT_NODE_SEPERATION_HORIZONTAL = 50;
export const DEFAULT_EDGE_INDENT = 30;
export const DEFAULT_FINALLLY_GROUP_PADDING = 20;
